version: '2.1'
networks:
  monitoring:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}
    db:
      driver: local
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - monitoring
  expensy-app:
    #cpus: 1 
    #mem_limit: 2048m
    #mem_reservation: 2048M
    volumes:
      - ./results:/usr/src/app/results 
    build:
      context: expensy-app
    ports:
      - 8080:8080
    expose:
      - 8080
      - 3306
    networks:
      - monitoring
  mysql:
    image: mysql:8.0.3
    networks:
      - monitoring
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
